### ISSUE TITLE
[Protocol3] Separate stakes for the exchange operator and the exchange owner

### ISSUE THREAD

**Issue by Brechtpd** [Loopring/protocols#131] opened 2019-04-10 04:04 UTC
We may need 2 different stakes for an exchange:
- A stake for the operator, which is burned when blocks are reverted or is used to pay the fine when the withdrawals aren't distributed by the operator
- A stake for the exchange, which is burned when the exchange goes into withdrawal mode. The only way this stake is not burned is when the exchange is shutdown and funds are distributed back to the users.

Currently there is only a single stake. So when a block is reverted the exchange doesn't have any incentive anymore to correctly shutdown the exchange.

Not sure yet what the best solution is here.

**Comment by dong77** [comment] 2019-06-05 03:23
This is a duplicate of #197 .

**Closed by dong77** 2019-06-05 03:23 UTC
Labels: enhancement
